// Generated by CoffeeScript 1.6.2
(function() {
  var __slice = [].slice;

  Function.prototype.acts_as = function() {
    var argv, cl, key, value, _i, _len, _ref;

    argv = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    for (_i = 0, _len = argv.length; _i < _len; _i++) {
      cl = argv[_i];
      this.prototype["__is" + cl] = true;
      _ref = cl.prototype;
      for (key in _ref) {
        value = _ref[key];
        this.prototype[key] = value;
      }
    }
    return this;
  };

}).call(this);
