// Generated by CoffeeScript 1.6.2
(function() {
  var A, B, C, i;

  require("../index");

  A = (function() {
    function A() {}

    A.toString = function() {
      return 'ClassA';
    };

    A.isA = function(obj) {
      if (obj != null) {
        return Boolean(obj["__is" + this]);
      } else {
        return false;
      }
    };

    A.prototype.a = function() {
      console.log("[A.a] called");
      return "AAA";
    };

    return A;

  })();

  B = (function() {
    function B() {}

    B.prototype.b = function() {
      console.log("[B.b] called");
      return "BBB";
    };

    return B;

  })();

  C = (function() {
    function C() {}

    C.acts_as(A, B);

    C.prototype.c = function() {
      console.log("[C.c] called");
      return "CCC";
    };

    return C;

  })();

  i = new C;

  console.dir(i);

  console.log("i.a():" + (i.a()));

  console.log("i.b():" + (i.b()));

  console.log("i.c():" + (i.c()));

  console.log("i behave like A? : " + (A.isA(i)));

}).call(this);
